package io.dockstore.client.cli.cwl;

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
/** Version symbols for published CWL document versions. */
@org.apache.avro.specific.AvroGenerated
public enum CWLVersions { 
  draft3dev1, draft3dev2  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CWLVersions\",\"doc\":\"Version symbols for published CWL document versions.\",\"symbols\":[\"draft3dev1\",\"draft3dev2\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
