package io.dockstore.client.cli.cwl;

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
/** Salad data types are based on Avro schema declarations.  Refer to the
[Avro schema declaration documentation](https://avro.apache.org/docs/current/spec.html#schemas) for
detailed information.

## Simple types

* **null**: no value
* **boolean**: a binary value
* **int**: 32-bit signed integer
* **long**: 64-bit signed integer
* **float**: single precision (32-bit) IEEE 754 floating-point number
* **double**: double precision (64-bit) IEEE 754 floating-point number
* **string**: Unicode character sequence
 */
@org.apache.avro.specific.AvroGenerated
public enum PrimitiveType { 
  null$, boolean$, int$, long$, float$, double$, string  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PrimitiveType\",\"doc\":\"Salad data types are based on Avro schema declarations.  Refer to the\\n[Avro schema declaration documentation](https://avro.apache.org/docs/current/spec.html#schemas) for\\ndetailed information.\\n\\n## Simple types\\n\\n* **null**: no value\\n* **boolean**: a binary value\\n* **int**: 32-bit signed integer\\n* **long**: 64-bit signed integer\\n* **float**: single precision (32-bit) IEEE 754 floating-point number\\n* **double**: double precision (64-bit) IEEE 754 floating-point number\\n* **string**: Unicode character sequence\\n\",\"symbols\":[\"null\",\"boolean\",\"int\",\"long\",\"float\",\"double\",\"string\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
