package cwl;
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Array_symbol { 
  array  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Array_symbol\",\"symbols\":[\"array\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
