package cwl;
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum File_class { 
  File  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"File_class\",\"symbols\":[\"File\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
