package cwl;
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
/** The input link merge method, described in [WorkflowStepInput](#WorkflowStepInput). */
@org.apache.avro.specific.AvroGenerated
public enum LinkMergeMethod { 
  merge_nested, merge_flattened  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LinkMergeMethod\",\"doc\":\"The input link merge method, described in [WorkflowStepInput](#WorkflowStepInput).\",\"symbols\":[\"merge_nested\",\"merge_flattened\"],\"docParent\":\"https://w3id.org/cwl/cwl#WorkflowStepInput\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
