package cwl;
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Record_symbol { 
  record  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Record_symbol\",\"symbols\":[\"record\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
